### ISSUE TITLE
Unable to build with 5.0.2 (TypeScript errors)

### ISSUE THREAD

**Issue by vthommeret** [googleapis/google-cloud-node#7485]
#### Environment details

  - OS: macOS 12.1
  - Node.js version: 16.13.2
  - npm version: 8.1.2
  - `@google-cloud/firestore` version: 5.0.2

#### Steps to reproduce

  1. Call `npm run build` within Firebase Functions folder

#### Output

```
[main] ./firebase/functions $ npm run build

> build
> tsc

node_modules/@google-cloud/firestore/types/firestore.d.ts:117:29 - error TS1005: ']' expected.

117     {[K in keyof T & string as `${Prefix}.${K}`]+?: T[K]};
                                ~~

node_modules/@google-cloud/firestore/types/firestore.d.ts:117:48 - error TS1005: ';' expected.

117     {[K in keyof T & string as `${Prefix}.${K}`]+?: T[K]};
                                                   ~

node_modules/@google-cloud/firestore/types/firestore.d.ts:117:50 - error TS1109: Expression expected.

117     {[K in keyof T & string as `${Prefix}.${K}`]+?: T[K]};
                                                     ~

node_modules/@google-cloud/firestore/types/firestore.d.ts:117:51 - error TS1109: Expression expected.

117     {[K in keyof T & string as `${Prefix}.${K}`]+?: T[K]};
                                                      ~

node_modules/@google-cloud/firestore/types/firestore.d.ts:2278:1 - error TS1128: Declaration or statement expected.

2278 }
     ~


Found 5 errors.
```

I see this on 5.0.0, 5.0.1, and 5.0.2. Running on 4.15.1 I see no errors.
