### ISSUE TITLE
Getting metadata from plugin failed with error: Could not refresh access token: Cannot find module

### ISSUE THREAD

**Issue by adamalmqvist10** [googleapis/google-cloud-node#6276]
Why does updating to @google-cloud/secret-manager v6.0.0 cause "Getting metadata from plugin failed with error: Could not refresh access token: Cannot find module ..."
Im getting this error after updating @google-cloud/secret-manager to 6.0.0 from 5.6.0.

**Comment by sofisl** [comment]
Please follow the template suggested when filling out a bug, including a full reproduction with environment and full error message.
